#!/bin/sh

if [[ $(uname -s) == Darwin* ]];then
  echo "Bootstrapping for MacOS... \n"
  sh -c $HOME/.config/yadm/macos.sh
else
  echo "Bootstrapping for Linux... \n"
  sh -c $HOME/.config/yadm/linux.sh
fi
